# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ae31d62be82d3e6fefb9f98e5e91f59c7172973e7cf46c61ae25292cbfd682db3474a87c5b8f0e205da1e643b87b575f65426f78f3dd72296bc8b75e1f9119a

test:
  secret_key_base: 1fe5261575339f37914e8244addf673d6e55528191f9c3ab231ebe30ab496e4c7c19a795d3ddae505a0d8d2c13a2b10cbb777a241387d97327128324f3055225

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
